services:

  trackswiftly_vehicle_service:
    # build: .
    image: lasthour/trackswiftly_vehicle_service:1.0.3
    environment:
      DB_HOST: postgres:5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}

    ports:
      - '${HOST_PORT:-8080}:8080'

    restart: unless-stopped
    networks:
      - keycloak-providers_keycloak_network

networks:
  keycloak-providers_keycloak_network:
    external: true
